include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/models/**/*.g.dart
  errors:
    missing_required_param: warning

linter:
  rules:
    public_member_api_docs: false
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true
