include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/models/**/*.g.dart
  errors:
    missing_required_param: warning

linter:
  rules:
    public_member_api_docs: false
    overridden_fields: false
