name: wfcd_api_wrapper
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 1.0.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  worldstate_model:
    git:
      url: https://github.com/SlayerOrnstein/worldstate_model.git
      ref: e66bfce2bd973eab1f91888e004c6d28e071051c 

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
