name: wfcd_api_wrapper
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 1.2.1
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  worldstate_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git
  warframe_items_model:
    git: https://github.com/SlayerOrnstein/warframe_item_models.git
  json_annotation: ^3.0.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  mockito: ^4.1.1
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
