name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.2.4
author: Ludwig <blacklightinglr@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  equatable: ^2.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  test: ^1.16.5
  very_good_analysis: ^2.0.0
