name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.10.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.6.0
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
