name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.0.1
author: Ludwig <blacklightinglr@gmail.com>
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  build_runner: ^1.10.11
  effective_dart: ^1.2.0
  json_serializable: ^3.5.1
  mockito: ^4.1.1
  test: ^1.6.0
