name: wfcd_api_wrapper
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 1.3.1+2
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  worldstate_api_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git
  warframe_items_model:
    git: https://github.com/SlayerOrnstein/warframe_item_models.git
  json_annotation: ^3.0.0
  equatable: ^1.0.1

dev_dependencies:
  test: ^1.6.0
  mockito: ^4.1.1
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
