name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.2.6
author: Ludwig <blacklightinglr@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  equatable: ^2.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.1.0
  mocktail: ^0.1.1
  test: ^1.16.5
  very_good_analysis: ^2.0.0
