name: wfcd_api_wrapper
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 1.0.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  worldstate_model:
    git: https://github.com/SlayerOrnstein/worldstate_model.git

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
