name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.7.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.4.0
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
  test: ^1.19.5
  very_good_analysis: ^2.4.0
