name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.0.1
author: Ludwig <blacklightinglr@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0-nullsafety.0
  http:
    git: https://github.com/dart-lang/http.git
  json_annotation: ^4.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.10.11
  effective_dart: ^1.2.0
  json_serializable: ^4.0.0-nullsafety.0
  mockito: ^5.0.0-nullsafety.1
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  http_parser: ^4.0.0-nullsafety
