name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 2.3.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  dartx: ^0.5.0
  dio: ^3.0.10
  equatable: ^1.2.5

dev_dependencies:
  effective_dart: ^1.2.0
  mockito: ^4.1.1
  test: ^1.6.0
