name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 3.6.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3
  json_annotation: ^4.0.1
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^4.1.3
  mocktail: ^0.1.4
  test: ^1.17.10
  very_good_analysis: ^2.3.0
