name: wfcd_client
description: Simple wrapper for worldstate api and maybe other WFCD APIs.
version: 2.2.0
author: Ludwig <blacklightinglr@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  warframestat_api_models:
    git: https://github.com/SlayerOrnstein/warframestat_api_models.git
  equatable: ^1.2.3
  dartx: ^0.5.0
  hive: ^1.4.1+1

dev_dependencies:
  test: ^1.6.0
  effective_dart: ^1.2.0
  mockito: ^4.1.1
