name: Dart CI
on:
  push:
    branches:
      - master
      - null-safe
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2.5.0
        with:
          release-channel: beta
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
